workflows:
  ios_no_sign:
    name: iOS (no signing) – XcodeGen
    max_build_duration: 60
    environment:
      xcode: 16.4
      groups:
        - app-secrets   # enthält OPENAI_API_KEY (+ optional SERP_API_KEY/BING_API_KEY)
    scripts:
      - name: Show macOS & Xcode
        script: |
          xcodebuild -version
          sw_vers

      - name: Install XcodeGen and generate .xcodeproj
        script: |
          set -euo pipefail
          if ! command -v xcodegen >/dev/null 2>&1; then
            brew update
            brew install xcodegen
          fi
          if [ ! -f project.yml ]; then
            echo "❌ project.yml not found in repo root."
            exit 66
          fi
          xcodegen generate
          if [ ! -d "TendersApp.xcodeproj" ]; then
            echo "❌ TendersApp.xcodeproj was not generated."
            exit 66
          fi
          echo "export PROJECT_PATH='TendersApp.xcodeproj'" >> "$CM_ENV"
          echo "export SCHEME='TendersApp'" >> "$CM_ENV"
          echo "✅ Generated TendersApp.xcodeproj and scheme TendersApp"

      - name: Resolve Swift Package dependencies (if any)
        script: |
          set -euo pipefail
          xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH" -scheme "$SCHEME"

      - name: Write API keys into Info.plist of the app target
        script: |
          set -euo pipefail
          SETTINGS=$(xcodebuild -showBuildSettings -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration Release)
          INFOPLIST_FILE=$(echo "$SETTINGS" | awk -F' = ' '/ INFOPLIST_FILE /{print $2; exit}')
          if [ -z "$INFOPLIST_FILE" ]; then
            echo "❌ Could not determine INFOPLIST_FILE"
            exit 1
          fi
          PLIST_PATH="$INFOPLIST_FILE"
          if [ ! -f "$PLIST_PATH" ]; then
            # falls relativ zum Projektordner
            PROJ_DIR=$(dirname "$PROJECT_PATH")
            if [ -f "$PROJ_DIR/$INFOPLIST_FILE" ]; then
              PLIST_PATH="$PROJ_DIR/$INFOPLIST_FILE"
            fi
          fi
          if [ ! -f "$PLIST_PATH" ]; then
            echo "❌ Info.plist not found at: $INFOPLIST_FILE"
            exit 1
          fi
          echo "✅ Using Info.plist: $PLIST_PATH"

          /usr/libexec/PlistBuddy -c "Delete :OPENAI_API_KEY" "$PLIST_PATH" || true
          /usr/libexec/PlistBuddy -c "Add :OPENAI_API_KEY string $OPENAI_API_KEY" "$PLIST_PATH"

          if [ -n "${SERP_API_KEY:-}" ]; then
            /usr/libexec/PlistBuddy -c "Delete :SERP_API_KEY" "$PLIST_PATH" || true
            /usr/libexec/PlistBuddy -c "Add :SERP_API_KEY string $SERP_API_KEY" "$PLIST_PATH"
          fi

          if [ -n "${BING_API_KEY:-}" ]; then
            /usr/libexec/PlistBuddy -c "Delete :BING_API_KEY" "$PLIST_PATH" || true
            /usr/libexec/PlistBuddy -c "Add :BING_API_KEY string $BING_API_KEY" "$PLIST_PATH"
          fi

      - name: Build iOS (no code signing)
        script: |
          set -euo pipefail
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - DerivedData/Build/Products/Release-iphoneos/*.app
      - $CM_BUILD_DIR/ResultBundle_*.xcresult

