workflows:
  ios_release_no_signing:
    name: iOS Release (no signing)
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        APP_PROJECT: TendersApp.xcodeproj
        APP_SCHEME: TendersApp
        CONFIGURATION: Release
      groups:
        - app-secrets     # <- genau so heißt die Gruppe, die du eben erstellt hast
    scripts:
      - name: Show Xcode version
        script: xcodebuild -version

      - name: Build iOS (no signing)
        script: |
          set -e
          xcodebuild \
            -project "$APP_PROJECT" \
            -scheme "$APP_SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

    artifacts:
      - DerivedData/Build/Products/**/*.app
      - DerivedData/Build/Products/**/*.ipa
    publishing:
      email:
        recipients:
          - your@email.tld
        notify:
          success: false
          failure: true

