workflows:
  ios_release:
    name: iOS Release
    environment:
      vars:
        XCODEGEN_VERSION: "2.37.0"
        BUNDLE_ID: "com.avanti.procurefinder"
        APP_NAME: "ProcureFinder"
      xcode: "15.4"
    triggering:
      events:
        - push
    scripts:
      - name: Install tools
        script: |
          brew install xcodegen || true
      - name: Generate Xcode project
        script: |
          xcodegen generate --spec project.yml
      - name: Generate App Icons
        script: |
          python3 scripts/gen_app_icons.py
      - name: Create export options (for signed export)
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>ad-hoc</string>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>manual</string>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST
      - name: Set build number
        script: |
          BUILD_NUMBER=$(date +%s)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "ProcureFinder/Info.plist"

      # === Build ===
      - name: Build (signed archive if vars present, else unsigned app)
        script: |
          set -e
          if [ -n "$CM_CERTIFICATE" ] && [ -n "$CM_PROVISIONING_PROFILE" ]; then
            # Signed ARCHIVE build (for direct signed IPA export)
            xcodebuild -project ProcureFinder.xcodeproj \
              -scheme ProcureFinder -configuration Release -sdk iphoneos \
              -destination generic/platform=iOS \
              clean archive -archivePath build/ProcureFinder.xcarchive
          else
            # UNSIGNED device build (for Sideloadly)
            xcodebuild -project ProcureFinder.xcodeproj \
              -scheme ProcureFinder -configuration Release -sdk iphoneos \
              -destination generic/platform=iOS \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              clean build -derivedDataPath build/Derived
          fi

      # === Export / Package ===
      - name: Export IPA (signed if vars present, else create unsigned IPA)
        script: |
          set -e
          if [ -n "$CM_CERTIFICATE" ] && [ -n "$CM_PROVISIONING_PROFILE" ]; then
            # Import signing material
            echo "$CM_CERTIFICATE" | base64 --decode > /tmp/cert.p12
            echo "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
            KEYCHAIN=build.keychain
            security create-keychain -p "" $KEYCHAIN
            security import /tmp/cert.p12 -k $KEYCHAIN -P "$CM_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
            security default-keychain -s $KEYCHAIN
            security unlock-keychain -p "" $KEYCHAIN
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

            # Export signed IPA from archive
            xcodebuild -exportArchive \
              -archivePath build/ProcureFinder.xcarchive \
              -exportOptionsPlist exportOptions.plist \
              -exportPath build/ipa
          else
            # Package UNSIGNED .ipa for Sideloadly
            APP_DIR="build/Derived/Build/Products/Release-iphoneos"
            mkdir -p build/Payload
            cp -R "$APP_DIR/ProcureFinder.app" build/Payload/ProcureFinder.app
            (cd build && zip -r ProcureFinder-unsigned.ipa Payload)
          fi
    artifacts:
      - build/ipa/*.ipa
      - build/ProcureFinder-unsigned.ipa
      - build/Derived/Build/Products/Release-iphoneos/ProcureFinder.app
      - build/ProcureFinder.xcarchive
      - xcodebuild.log


