workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA (for Sideloadly)
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        SCHEME: TendersApp           # <— ggf. anpassen
        CONFIGURATION: Release
        DERIVED_DATA: $CM_BUILD_DIR/DerivedData
    scripts:
      - name: Prepare project (optionales XcodeGen)
        script: |
          set -euo pipefail
          # Falls ein XcodeGen-Spec vorhanden ist, generieren
          if [ -f project.yml ]; then
            brew install xcodegen || true
            xcodegen generate
          fi
          # .xcworkspace bevorzugen, sonst .xcodeproj
          if ls -1 *.xcworkspace 1>/dev/null 2>&1; then
            export CONTAINER=$(ls -1 *.xcworkspace | head -n1)
            export PROJECT_FLAG="-workspace \"$CONTAINER\""
          elif ls -1 *.xcodeproj 1>/dev/null 2>&1; then
            export CONTAINER=$(ls -1 *.xcodeproj | head -n1)
            export PROJECT_FLAG="-project \"$CONTAINER\""
          else
            echo "Kein .xcworkspace oder .xcodeproj gefunden."
            exit 1
          fi
          echo "Nutze: $CONTAINER  |  Scheme: $SCHEME"

      - name: Build (no signing)
        script: |
          set -euo pipefail
          # build, keine Signierung
          eval xcodebuild $PROJECT_FLAG \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            build

      - name: Package unsigned .ipa
        script: |
          set -euo pipefail
          APP_PATH=$(find "$DERIVED_DATA/Build/Products/$CONFIGURATION-iphoneos" -type d -name "*.app" -print -quit)
          test -n "$APP_PATH" || { echo "Keine .app gefunden"; exit 1; }
          echo "App gefunden: $APP_PATH"
          rm -rf Payload
          mkdir -p Payload build/ipa
          cp -R "$APP_PATH" Payload/
          IPA_NAME="TendersApp-unsigned-${CM_BUILD_ID}.ipa"
          (zip -qry "build/ipa/$IPA_NAME" Payload)
          rm -rf Payload
          ls -lah build/ipa

    artifacts:
      - build/ipa/*.ipa
      - $DERIVED_DATA/Build/Products/$CONFIGURATION-iphoneos/*.app
      - $DERIVED_DATA/Logs/**/*.log

    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true

