workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    environment:
      xcode: 15.4
    scripts:
      - name: Show repo tree (debug)
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la
          echo "----"
          ls -la ProcureFinder || true

      - name: Install XcodeGen
        script: |
          brew install xcodegen || true
          xcodegen --version

      - name: Generate Xcode project from project.yml
        script: |
          if [ -f project.yml ]; then
            xcodegen generate
          fi
          test -d ProcureFinder.xcodeproj || { echo "ProcureFinder.xcodeproj missing"; exit 1; }

      - name: Set build number
        script: |
          set -e
          BUILD_NUM=${CM_BUILD_ID:-1}
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUM}" ProcureFinder/Info.plist

      - name: Generate App Icons
        script: |
          python3 ProcureFinder/Scripts/gen_app_icons.py || true

      - name: Build (unsigned by default; signed archive if vars present)
        script: |
          set -euo pipefail
          APP_NAME="ProcureFinder"
          PROJECT_PATH="$CM_BUILD_DIR/ProcureFinder.xcodeproj"
          SCHEME="$APP_NAME"
          BUILD_DIR="$CM_BUILD_DIR/build"
          mkdir -p "$BUILD_DIR"

          if [ -n "${CM_PROVISIONING_PROFILE:-}" ] || [ -n "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]; then
            echo "Signed archive path"
            xcodebuild -project "$PROJECT_PATH" \
              -scheme "$SCHEME" -configuration Release -sdk iphoneos \
              -archivePath "$BUILD_DIR/${APP_NAME}.xcarchive" clean archive
          else
            echo "UNSIGNED device build path"
            xcodebuild -project "$PROJECT_PATH" \
              -scheme "$SCHEME" -configuration Release -sdk iphoneos \
              -destination generic/platform=iOS \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY= \
              clean build -derivedDataPath "$BUILD_DIR/Derived"
          fi

      - name: Export / Package IPA
        script: |
          set -euo pipefail
          APP_NAME="ProcureFinder"
          BUILD_DIR="$CM_BUILD_DIR/build"
          DERIVED="$BUILD_DIR/Derived"
          APP_PATH="$DERIVED/Build/Products/Release-iphoneos/${APP_NAME}.app"
          ARCHIVE_PATH="$BUILD_DIR/${APP_NAME}.xcarchive"
          OUT_DIR="$BUILD_DIR/ipa"
          LOG_PATH="$BUILD_DIR/xcodebuild_export.log"

          rm -rf "$OUT_DIR"
          mkdir -p "$OUT_DIR"

          if [ -d "$ARCHIVE_PATH" ]; then
            echo "Found archive -> exporting signed IPA"
            EXPORT_PLIST="$BUILD_DIR/exportOptions.plist"
            /usr/libexec/PlistBuddy -c 'Clear dict' "$EXPORT_PLIST" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c 'Add :method string ad-hoc' "$EXPORT_PLIST"
            /usr/libexec/PlistBuddy -c 'Add :compileBitcode bool false' "$EXPORT_PLIST"
            /usr/libexec/PlistBuddy -c 'Add :stripSwiftSymbols bool true' "$EXPORT_PLIST"
            /usr/libexec/PlistBuddy -c 'Add :destination string export' "$EXPORT_PLIST"
            /usr/libexec/PlistBuddy -c 'Add :thinning string <none>' "$EXPORT_PLIST"

            xcodebuild -exportArchive \
              -archivePath "$ARCHIVE_PATH" \
              -exportPath "$OUT_DIR" \
              -exportOptionsPlist "$EXPORT_PLIST" \
              -allowProvisioningUpdates | tee "$LOG_PATH"
          else
            echo "No archive -> package UNSIGNED IPA for Sideloadly"
            if [ ! -d "$APP_PATH" ]; then
              echo "ERROR: App bundle not found at $APP_PATH"
              exit 1
            fi
            PAYLOAD_DIR="_



