    scripts:
      - name: "Build .app (unsigned, device)"
        script: |
          set -euxo pipefail
          DERIVED="$CM_BUILD_DIR/Derived"
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY= \
            -derivedDataPath "$DERIVED" \
            build

          APP_DIR="$DERIVED/Build/Products/Release-iphoneos/${SCHEME}.app"
          test -d "$APP_DIR" || { echo "Built .app not found: $APP_DIR"; ls -la "$DERIVED/Build/Products/Release-iphoneos" || true; exit 65; }

          echo "Validating Info.plist…"
          PLIST="$APP_DIR/Info.plist"

          # 1) Wenn CFBundleIdentifier fehlt/leer ist: setzen wir ihn hart, damit Sideloadly arbeiten kann
          BID=$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "$PLIST" 2>/dev/null || true)
          if [ -z "${BID:-}" ] || [[ "$BID" == *'$('* ]] || [[ "$BID" == *PRODUCT_BUNDLE_IDENTIFIER* ]]; then
            echo "Fixing CFBundleIdentifier in built app Info.plist…"
            /usr/libexec/PlistBuddy -c "Delete :CFBundleIdentifier" "$PLIST" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string com.avanti.procurefinder" "$PLIST"
          fi

          echo "CFBundleIdentifier now =" \
            "$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "$PLIST")"

      - name: "Package unsigned IPA (for Sideloadly)"
        script: |
          set -euxo pipefail
          DERIVED="$CM_BUILD_DIR/Derived"
          APP_DIR="$DERIVED/Build/Products/Release-iphoneos/${SCHEME}.app"

          rm -rf Payload ProcureFinder-unsigned.ipa ProcureFinder.app.zip
          mkdir -p Payload
          rsync -a --delete "$APP_DIR" "Payload/"

          # Doppelt hält besser: validate vor dem Zip
          /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "Payload/${SCHEME}.app/Info.plist" >/dev/null

          (cd Payload && zip -qry "../ProcureFinder-unsigned.ipa" .)
          zip -qry "ProcureFinder.app.zip" "Payload/${SCHEME}.app"





