workflows:
  ios_unsigned_ipa:
    name: Build unsigned IPA (for Sideloadly)
    max_build_duration: 60
    environment:
      xcode: 16.0
      vars:
        SCHEME: TendersApp
        BUNDLE_ID: com.aaron.schmidt.tenders

    scripts:
      # 1) Korrekte project.yml SCHREIBEN (passt zu deiner Repo-Struktur im Root)
      - name: Provide project.yml (matches current repo layout)
        script: |
          cat > project.yml <<'YML'
          name: TendersApp
          options:
            bundleIdPrefix: com.aaron.schmidt
          targets:
            TendersApp:
              type: application
              platform: iOS
              deploymentTarget: "16.0"
              sources:
                - path: .            # <-- WICHTIG: Code liegt im Root (Views, Models, Services, ...)
              info:
                path: Info.plist     # <-- Deine Info.plist liegt im Root
              settings:
                PRODUCT_BUNDLE_IDENTIFIER: com.aaron.schmidt.tenders
                CODE_SIGN_STYLE: Manual
          YML
          echo "Wrote project.yml"

      # 2) XcodeGen installieren und Xcode-Projekt erzeugen
      - name: Install XcodeGen & generate project
        script: |
          brew install xcodegen
          xcodegen generate
          ls -la

      # 3) Release-Build OHNE Codesigning (iphoneOS)
      - name: Build Release (no code signing)
        script: |
          set -e
          DERIVED="$CM_BUILD_DIR/DerivedData"
          xcodebuild \
            -project TendersApp.xcodeproj \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath "$DERIVED" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            build
          echo "DERIVED=$DERIVED" >> $CM_ENV

      # 4) .app zu *unsignierter* .ipa packen
      - name: Package unsigned .ipa
        script: |
          set -e
          APP_PATH=$(find "$DERIVED/Build/Products/Release-iphoneos" -maxdepth 1 -type d -name "*.app" | head -n 1)
          echo "Found app at: $APP_PATH"
          mkdir -p "$CM_BUILD_DIR/Payload"
          cp -R "$APP_PATH" "$CM_BUILD_DIR/Payload/TendersApp.app"
          (cd "$CM_BUILD_DIR" && zip -qry "TendersApp-unsigned.ipa" Payload)

    artifacts:
      - $CM_BUILD_DIR/TendersApp-unsigned.ipa
      - $CM_BUILD_DIR/DerivedData/Build/Products/Release-iphoneos/*.app
