workflows:
  ios_release:
    name: iOS Release
    environment:
      vars:
        XCODEGEN_VERSION: "2.37.0"
        BUNDLE_ID: "com.avanti.procurefinder"
        APP_NAME: "ProcureFinder"
      xcode: "15.4"
    triggering:
      events:
        - push
    scripts:
      - name: Install tools
        script: |
          brew install xcodegen || true
      - name: Generate Xcode project
        script: |
          xcodegen generate --spec project.yml
      - name: Generate App Icons
        script: |
          ICON_DIR="ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset"
          BASE="Icon-1024.png"
          python3 - << 'PY'
from random import randint
w=h=1024
# create a simple PPM image without external libs
with open("ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.ppm","w") as f:
    f.write(f"P3\n{w} {h}\n255\n")
    for y in range(h):
        row = []
        for x in range(w):
            row.append("0 122 255")
        f.write(" ".join(row)+"\n")
PY
          sips -s format png ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.ppm --out ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png >/dev/null
          rm ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.ppm
          # derive sizes
          sips -Z 40  ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-20@2x.png" >/dev/null
          sips -Z 60  ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-20@3x.png" >/dev/null
          sips -Z 58  ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-29@2x.png" >/dev/null
          sips -Z 87  ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-29@3x.png" >/dev/null
          sips -Z 80  ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-40@2x.png" >/dev/null
          sips -Z 120 ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-40@3x.png" >/dev/null
          sips -Z 120 ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-60@2x.png" >/dev/null
          sips -Z 180 ProcureFinder/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png --out "$ICON_DIR/Icon-60@3x.png" >/dev/null
      - name: Set build number
        script: |
          BUILD_NUMBER=$(date +%s)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "ProcureFinder/Info.plist"
      - name: Resolve dependencies
        script: |
          xcodebuild -version
      - name: Build .ipa
        script: |
          set -e
          xcodebuild -workspace "" -list || true
          xcodebuild -project ProcureFinder.xcodeproj -scheme ProcureFinder -configuration Release -sdk iphoneos -destination generic/platform=iOS clean build CODE_SIGN_STYLE=Manual || true
          # Signing
          if [ -n "$CM_CERTIFICATE" ] && [ -n "$CM_PROVISIONING_PROFILE" ]; then
            echo "$CM_CERTIFICATE" | base64 --decode > /tmp/cert.p12
            echo "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
            KEYCHAIN=build.keychain
            security create-keychain -p "" $KEYCHAIN
            security import /tmp/cert.p12 -k $KEYCHAIN -P "$CM_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
            security default-keychain -s $KEYCHAIN
            security unlock-keychain -p "" $KEYCHAIN
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          fi
          xcodebuild -project ProcureFinder.xcodeproj -scheme ProcureFinder -configuration Release -sdk iphoneos -destination generic/platform=iOS build
          xcodebuild -exportArchive -archivePath build/ProcureFinder.xcarchive -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string><key>compileBitcode</key><false/></dict></plist>') -exportPath build/ipa || true
    artifacts:
      - build/ipa/*.ipa
      - build/*.xcarchive
      - ProcureFinder.app
      - xcodebuild.log
