workflows:
  ios_no_sign:
    name: iOS Build (no signing)
    environment:
      xcode: latest
      vars:
        OPENAI_API_KEY: Encrypted(…)
        SERP_API_KEY: Encrypted(…) # oder BING_API_KEY
    scripts:
      - name: Clean
        script: |
          rm -rf DerivedData
      - name: Resolve Swift Packages
        script: |
          xcodebuild \
            -project TenderSmartApp.xcodeproj \
            -scheme TenderSmartApp \
            -resolvePackageDependencies
      - name: Build Release (no signing)
        script: |
          xcodebuild \
            -project TenderSmartApp.xcodeproj \
            -scheme TenderSmartApp \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath DerivedData \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            build
      - name: Package .ipa for Sideloadly
        script: |
          APP_PATH=$(find DerivedData/Build/Products/Release-iphoneos -maxdepth 1 -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "App (.app) nicht gefunden" && exit 1
          fi
          rm -rf Payload TenderSmartApp.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r TenderSmartApp.ipa Payload
    artifacts:
      - TenderSmartApp.ipa
      - DerivedData/Build/Products/Release-iphoneos/*.app
