workflows:
  ios_release:
    name: iOS Release (Sideloadly)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      # Wichtig: Projektformat 77 benötigt Xcode 16.x
      # Verfügbar auf Codemagic (16.0/16.4 sind Images). 
      # Siehe Codemagic Xcode 16 Specs.
      xcode: 16.4
      vars:
        APP_SCHEME: "ProcureFinder"
        APP_PROJECT: "ProcureFinder.xcodeproj"
        BUILD_CONFIGURATION: "Release"
        DERIVED_DATA: "$CM_BUILD_DIR/build/Derived"

    triggering:
      events:
        - push

    scripts:
      - name: Xcode & Swift Version anzeigen
        script: |
          set -euo pipefail
          xcodebuild -version
          swift --version

      - name: Build-Nummer automatisch setzen (CFBundleVersion)
        script: |
          set -euo pipefail
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "ProcureFinder/Info.plist"
          echo "CFBundleVersion=$BUILD_NUMBER gesetzt"

      - name: Clean
        script: |
          set -euo pipefail
          rm -rf "$DERIVED_DATA" build || true
          mkdir -p "$DERIVED_DATA"

      - name: Build .app (unsigned, für Gerät)
        script: |
          set -euo pipefail
          xcodebuild build \
            -project "$APP_PROJECT" \
            -scheme "$APP_SCHEME" \
            -configuration "$BUILD_CONFIGURATION" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY= \
            -derivedDataPath "$DERIVED_DATA"
          
          APP_PATH="$DERIVED_DATA/Build/Products/$BUILD_CONFIGURATION-iphoneos/$APP_SCHEME.app"
          test -d "$APP_PATH"
          echo "APP_PATH=$APP_PATH"

      - name: Package unsigned IPA (für Sideloadly)
        script: |
          set -euo pipefail
          APP_PATH="$DERIVED_DATA/Build/Products/$BUILD_CONFIGURATION-iphoneos/$APP_SCHEME.app"
          PKG_DIR="$CM_BUILD_DIR/pkg"
          mkdir -p "$PKG_DIR/Payload"
          cp -R "$APP_PATH" "$PKG_DIR/Payload/$APP_SCHEME.app"
          (cd "$PKG_DIR" && /usr/bin/zip -qry "../$APP_SCHEME-unsigned.ipa" Payload)
          echo "IPA_PATH=$CM_BUILD_DIR/$APP_SCHEME-unsigned.ipa"

    artifacts:
      - $CM_BUILD_DIR/$APP_SCHEME-unsigned.ipa
      - $DERIVED_DATA/Build/Products/$BUILD_CONFIGURATION-iphoneos/$APP_SCHEME.app
      - /tmp/xcodebuild_logs/*.log

    # Absichtlich kein 'publishing:' Block, damit keine E-Mail-Validierung greift

