workflows:
  ios_no_sign:
    name: iOS (no signing)
    max_build_duration: 60
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        PROJECT: "TendersApp.xcodeproj"
        SCHEME: "TendersApp"
      groups:
        - app-secrets   # enthält OPENAI_API_KEY, SERP_API_KEY (optional BING_API_KEY)
    scripts:
      - name: Show macOS & Xcode
        script: |
          xcodebuild -version
          sw_vers

      - name: Resolve Swift Package dependencies
        script: |
          xcodebuild -resolvePackageDependencies -project "$PROJECT" -scheme "$SCHEME"

      - name: Write API keys into Info.plist
        script: |
          set -e
          PLIST="Info.plist"
          if [ ! -f "$PLIST" ]; then
            echo "Info.plist not found at repo root"; exit 1
          fi

          # OPENAI_API_KEY (required)
          /usr/libexec/PlistBuddy -c "Delete :OPENAI_API_KEY" "$PLIST" || true
          /usr/libexec/PlistBuddy -c "Add :OPENAI_API_KEY string $OPENAI_API_KEY" "$PLIST"

          # SERP_API_KEY (optional)
          if [ -n "$SERP_API_KEY" ]; then
            /usr/libexec/PlistBuddy -c "Delete :SERP_API_KEY" "$PLIST" || true
            /usr/libexec/PlistBuddy -c "Add :SERP_API_KEY string $SERP_API_KEY" "$PLIST"
          fi

          # BING_API_KEY (optional)
          if [ -n "$BING_API_KEY" ]; then
            /usr/libexec/PlistBuddy -c "Delete :BING_API_KEY" "$PLIST" || true
            /usr/libexec/PlistBuddy -c "Add :BING_API_KEY string $BING_API_KEY" "$PLIST"
          fi

      - name: Build (no code signing)
        script: |
          set -e
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - DerivedData/Build/Products/Release-iphoneos/*.app
      - $CM_BUILD_DIR/ResultBundle_*.xcresult
    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true

