workflows:
  ios_unsigned_ipa:
    name: Build unsigned IPA for Sideloadly
    max_build_duration: 60
    environment:
      xcode: 15.4
      vars:
        SCHEME: TendersApp
        BUNDLE_ID: com.aaron.schmidt.tenders
    scripts:
      - name: Install Xcode project dependencies
        script: |
          gem install cocoapods
          pod install --repo-update || pod install
      - name: Build unsigned IPA
        script: |
          xcodebuild -scheme "$SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $CM_BUILD_DIR/Build.xcarchive \
          archive CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/Build.xcarchive \
          -exportOptionsPlist /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Templates/Project\ Templates/iOS/Application\ with\ WatchKit\ App.xctemplate/ExportOptions.plist \
          -exportPath $CM_BUILD_DIR/ipa \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ipa
      - dSYM
