workflows:
  ios_release:
    name: iOS Release
    environment:
      vars:
        XCODEGEN_VERSION: "2.37.0"
        BUNDLE_ID: "com.avanti.procurefinder"
        APP_NAME: "ProcureFinder"
      xcode: "15.4"
    triggering:
      events:
        - push
    scripts:
      - name: Install tools
        script: |
          brew install xcodegen || true
      - name: Generate Xcode project
        script: |
          xcodegen generate --spec project.yml
      - name: Generate App Icons
        script: |
          python3 scripts/gen_app_icons.py
      - name: Create export options
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>ad-hoc</string>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>manual</string>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST
      - name: Set build number
        script: |
          BUILD_NUMBER=$(date +%s)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "ProcureFinder/Info.plist"
      - name: Build archive
        script: |
          set -e
          xcodebuild -project ProcureFinder.xcodeproj -scheme ProcureFinder -configuration Release -sdk iphoneos -destination generic/platform=iOS clean archive -archivePath build/ProcureFinder.xcarchive CODE_SIGN_STYLE=Manual || true
      - name: Sign and export IPA
        script: |
          set -e
          if [ -n "$CM_CERTIFICATE" ] && [ -n "$CM_PROVISIONING_PROFILE" ]; then
            echo "$CM_CERTIFICATE" | base64 --decode > /tmp/cert.p12
            echo "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
            KEYCHAIN=build.keychain
            security create-keychain -p "" $KEYCHAIN
            security import /tmp/cert.p12 -k $KEYCHAIN -P "$CM_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
            security default-keychain -s $KEYCHAIN
            security unlock-keychain -p "" $KEYCHAIN
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          fi
          xcodebuild -exportArchive -archivePath build/ProcureFinder.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
      - build/ProcureFinder.xcarchive
      - xcodebuild.log
