name: TendersApp

options:
  developmentLanguage: de
  bundleIdPrefix: com.aaron.schmidt    # <— ggf. ändern

targets:
  TendersApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - DerivedData
          - build
          - .build
          - README.md
          - codemagic.yaml
          - project.yml
    resources:
      - Assets.xcassets                 # <— existiert bei dir
      - LaunchScreen.storyboard         # <— falls du keinen LaunchScreen hast: Zeile löschen
    info:
      path: Info.plist                  # <— Pfad prüfen
    settings:
      PRODUCT_NAME: TendersApp
      PRODUCT_BUNDLE_IDENTIFIER: com.aaron.schmidt.tenders   # <— ggf. ändern
      SWIFT_VERSION: 5.10
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
    scheme:
      testTargets: []
