name: TendersApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.aaron.schmidt.tenders
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    INFOPLIST_FILE: Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    TARGETED_DEVICE_FAMILY: "1,2"   # iPhone + iPad (Fullscreen auf modernen Geräten)

targets:
  TendersApp:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - codemagic.yaml
          - project.yml
          - README.md
          - .gitignore
    resources:
      - Assets.xcassets
      - LaunchScreen.storyboard
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0

schemes:
  TendersApp:
    build:
      targets:
        TendersApp: all
    run:
      config: Release
    archive:
      config: Release
