name: TendersApp
options:
  minimumXcodeGenVersion: 2.33.0

targets:
  TendersApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - DerivedData
          - README.md
          - codemagic.yaml
    resources:
      - path: Assets.xcassets
      - path: LaunchScreen.storyboard
      - path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aaron.schmidt.tenders
      PRODUCT_NAME: TendersApp
      EXECUTABLE_NAME: TendersApp
      INFOPLIST_FILE: Info.plist
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      SWIFT_VERSION: 5.10
      TARGETED_DEVICE_FAMILY: "1"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    scheme:
      gatherCoverageData: false
