name: ProcureFinder
options:
  deploymentTarget:
    iOS: "16.0"
  minimumXcodeGenVersion: 2.37.0

packages: {}

targets:
  ProcureFinder:
    type: application
    platform: iOS
    sources:
      - path: ProcureFinder/Sources
      - path: ProcureFinder/Resources
        excludes:
          - LaunchScreen.storyboard
        includes:
          - Assets.xcassets
          - cpv.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.avanti.procurefinder
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: ProcureFinder/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - ProcureFinderTests
        - ProcureFinderUITests

  ProcureFinderTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ProcureFinderTests]
    dependencies:
      - target: ProcureFinder

  ProcureFinderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [ProcureFinderUITests]
    dependencies:
      - target: ProcureFinder
