name: ProcureFinder

options:
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    PRODUCT_BUNDLE_IDENTIFIER: com.avanti.procurefinder
    PRODUCT_NAME: ProcureFinder

targets:
  ProcureFinder:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        INFOPLIST_FILE: ProcureFinder/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    sources:
      - path: ProcureFinder/Sources
        excludes:
          - "**/*.md"
      - path: ProcureFinder/Resources
        type: folder
    resources:
      - ProcureFinder/Resources/Assets.xcassets
      - ProcureFinder/Resources/LaunchScreen.storyboard
      - ProcureFinder/Resources/cpv.json
      - ProcureFinder/Info.plist
    scheme:
      testTargets: []

  ProcureFinderTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - ProcureFinderTests
    dependencies:
      - target: ProcureFinder

  ProcureFinderUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - ProcureFinderUITests
    dependencies:
      - target: ProcureFinder

