name: TendersApp
options:
  bundleIdPrefix: com.example
targets:
  TendersApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: TendersApp
    info:
      path: TendersApp/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.TendersApp
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: YOUR_TEAM_ID