name: TendersApp

options:
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.0

targets:
  TendersApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    # NUR diese Quellen ins Target aufnehmen
    sources:
      - path: TendersApp.swift
      - path: Models
      - path: Views
      - path: Services
      - path: ViewModels
      - path: DesignSystem

    # Ressourcen (falls vorhanden)
    resources:
      - path: Assets.xcassets
        optional: true

    settings:
      INFOPLIST_FILE: Info.plist

schemes:
  TendersApp:
    build:
      targets:
        TendersApp: all

