name: TendersApp
options:
  minimumXcodeGenVersion: 2.33.0
  deploymentTarget:
    iOS: "16.0"

targets:
  TendersApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - .git/**            # << NEU: verhindert Kopieren von Git-Hooks in die App
          - project.yml        # << NEU: kommt sonst als Ressource in die .app
          - DerivedData
          - README.md
          - codemagic.yaml
          # Favorites vorerst deaktiviert:
          - Views/FavoritesView.swift
          - Services/FavoritesManager.swift
    resources:
      - path: Assets.xcassets
      - path: LaunchScreen.storyboard
      - path: Info.plist
    settings:
      PRODUCT_NAME: TendersApp
      PRODUCT_BUNDLE_IDENTIFIER: com.aaron.schmidt.tenders
      INFOPLIST_FILE: Info.plist
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      SWIFT_VERSION: 5.10
      TARGETED_DEVICE_FAMILY: "1"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    scheme:
      name: TendersApp
      gatherCoverageData: false
