name: ProcureFinder
options:
  deploymentTarget:
    iOS: "16.0"

targets:
  ProcureFinder:
    type: application
    platform: iOS
    sources:
      - path: ProcureFinder/Sources
      - path: ProcureFinder/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.avanti.procurefinder
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: ProcureFinder/Info.plist
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"


