name: ProcureFinder

options:
  minimumXcodeGenVersion: 2.30.0
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO

targets:
  ProcureFinder:
    type: application
    platform: iOS
    bundleId: com.avanti.procurefinder
    sources:
      - path: ProcureFinder/Sources
      - path: ProcureFinder/Resources
        type: folder
    info:
      path: ProcureFinder/Info.plist
    settings:
      base:
        INFOPLIST_FILE: ProcureFinder/Info.plist

  ProcureFinderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ProcureFinderTests
    settings:
      base:
        INFOPLIST_FILE: ProcureFinderTests/Info.plist
        CODE_SIGNING_ALLOWED: NO

  ProcureFinderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ProcureFinderUITests
    settings:
      base:
        INFOPLIST_FILE: ProcureFinderUITests/Info.plist
        CODE_SIGNING_ALLOWED: NO


